import type { User } from '~/lib/types/user';
import { Color } from '~/lib/types/user';

const imgUrl = '/img1.jpeg';
export const USERS: Array<User> = [
  {
    color: Color.RED,
    name: 'Test UserAKDSJHJ SAKDHJASDHJAS HDJKHSAKJDHSKAJDHKJHAD JKHASJKDHJKASHDKHSAKDHSAKJDHJSADHKJASHDKJADHKJD',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
  {
    color: Color.RED,
    name: 'Test User',
    time: '00:00:00',
    speed: '80',
    avatar: imgUrl,
  },
];
